name: geo_engine_sdk
description: SDK oficial para Geo-Engine. Rastreo de ubicación y gestión de geocercas.
version: 1.0.3
homepage: https://geoengine.dev

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8